import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Provider from "./provider"; 
import { ThemeProvider } from "components/ui/theme-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Provider>
          {children}
          </Provider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
